<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BG83L86" failures="2" tests="13" name="Test" time="5.784" errors="0" timestamp="2023-12-14T10:58:06 IST">
  <testcase classname="testcases.StatusFolder" name="verifyAddStatusWithoutAuthorization" time="0.846"/>
  <testcase classname="testcases.StatusFolder" name="verifyGetAllStatusWithoutAuthorization" time="0.049"/>
  <testcase classname="testcases.StatusFolder" name="verifyUpdateStatusWithoutAuthorization" time="0.03"/>
  <testcase classname="testcases.StatusFolder" name="deleteSingleStatusWithoutAuthorization" time="0.042"/>
  <testcase classname="testcases.StatusFolder" name="verifyAddStatusWithAuthorization" time="1.022">
    <failure type="java.lang.AssertionError" message="Status Already Exists expected [201] but found [422]">
      <![CDATA[java.lang.AssertionError: Status Already Exists expected [201] but found [422]
at testcases.StatusFolder.verifyAddStatusWithAuthorization(StatusFolder.java:121)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddStatusWithAuthorization -->
  <testcase classname="testcases.StatusFolder" name="addStatusWithSamePayloadAsPrevious" time="0.505"/>
  <testcase classname="testcases.StatusFolder" name="addStatusWithInvalidPayload" time="0.523"/>
  <testcase classname="testcases.StatusFolder" name="verifyGetAllStatusWithAuthorization" time="0.551"/>
  <testcase classname="testcases.StatusFolder" name="updateStatusWithAuthorization" time="0.001">
    <skipped/>
  </testcase> <!-- updateStatusWithAuthorization -->
  <testcase classname="testcases.StatusFolder" name="updateStatusWithoutGivingStatusId" time="0.484"/>
  <testcase classname="testcases.StatusFolder" name="updateStatusByGivingNonExistingStatusId" time="0.554"/>
  <testcase classname="testcases.StatusFolder" name="deleteSingleStatusWithAuthorization" time="0.001">
    <skipped/>
  </testcase> <!-- deleteSingleStatusWithAuthorization -->
  <testcase classname="testcases.StatusFolder" name="deleteSingleStatusWithInvalidStatusName" time="0.565">
    <failure type="java.lang.AssertionError" message="expected [No status to delete with Bass.] but found [No status to delete with Lind,Bass.]">
      <![CDATA[java.lang.AssertionError: expected [No status to delete with Bass.] but found [No status to delete with Lind,Bass.]
at testcases.StatusFolder.deleteSingleStatusWithInvalidStatusName(StatusFolder.java:357)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- deleteSingleStatusWithInvalidStatusName -->
</testsuite> <!-- Test -->
