<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BG83L86" failures="11" tests="85" name="Test" time="38.358" errors="0" timestamp="2023-12-16T10:10:39 IST">
  <testcase classname="testcases.ProjectFolder" name="verifyAddProjectWithoutAuthorization" time="1.945"/>
  <testcase classname="testcases.ProjectFolder" name="verifyGetAllProjectWithoutAuthorization" time="0.049"/>
  <testcase classname="testcases.ProjectFolder" name="verifyAddProjectWithAuthorization" time="1.029"/>
  <testcase classname="testcases.ProjectFolder" name="addProjectWithSamePayloadAsPrevious" time="0.425"/>
  <testcase classname="testcases.ProjectFolder" name="addProjectWithInvalidPayload" time="2.567"/>
  <testcase classname="testcases.ProjectFolder" name="addProjectWithoutGivingProjectStartDateInPayload" time="0.474"/>
  <testcase classname="testcases.ProjectFolder" name="verifyGetAllProjectWithAuthorization" time="0.402"/>
  <testcase classname="testcases.StatusFolder" name="verifyAddStatusWithoutAuthorization" time="0.031"/>
  <testcase classname="testcases.StatusFolder" name="verifyGetAllStatusWithoutAuthorization" time="0.038"/>
  <testcase classname="testcases.StatusFolder" name="verifyUpdateStatusWithoutAuthorization" time="0.041"/>
  <testcase classname="testcases.StatusFolder" name="deleteSingleStatusWithoutAuthorization" time="0.044"/>
  <testcase classname="testcases.StatusFolder" name="verifyAddStatusWithAuthorization" time="1.241">
    <failure type="java.lang.AssertionError" message="expected [No status to delete with Runolfsdottir.] but found [No status to delete with Passed,Runolfsdottir.]">
      <![CDATA[java.lang.AssertionError: expected [No status to delete with Runolfsdottir.] but found [No status to delete with Passed,Runolfsdottir.]
at testcases.StatusFolder.deleteSingleStatusWithAuthorization(StatusFolder.java:393)
at testcases.StatusFolder.verifyAddStatusWithAuthorization(StatusFolder.java:135)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddStatusWithAuthorization -->
  <testcase classname="testcases.StatusFolder" name="addStatusWithSamePayloadAsPrevious" time="0.54"/>
  <testcase classname="testcases.StatusFolder" name="addStatusWithInvalidPayload" time="0.424"/>
  <testcase classname="testcases.StatusFolder" name="addStatusWithSameStatusLevelInPayloadAsPrevious" time="0.491"/>
  <testcase classname="testcases.StatusFolder" name="verifyGetAllStatusWithAuthorization" time="0.391"/>
  <testcase classname="testcases.StatusFolder" name="updateStatusWithAuthorization" time="0.622"/>
  <testcase classname="testcases.StatusFolder" name="updateStatusWithoutGivingStatusId" time="0.499"/>
  <testcase classname="testcases.StatusFolder" name="updateStatusByGivingNonExistingStatusId" time="0.531"/>
  <testcase classname="testcases.StatusFolder" name="deleteSingleStatusWithInvalidStatusName" time="0.518">
    <failure type="java.lang.AssertionError" message="expected [No status to delete with Stopped.] but found [No status to delete with Passed,Runolfsdottir,Stopped.]">
      <![CDATA[java.lang.AssertionError: expected [No status to delete with Stopped.] but found [No status to delete with Passed,Runolfsdottir,Stopped.]
at testcases.StatusFolder.deleteSingleStatusWithInvalidStatusName(StatusFolder.java:440)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- deleteSingleStatusWithInvalidStatusName -->
  <testcase classname="testcases.DesignationFolder" name="verifyAddDesignationWithoutAuthorization" time="0.05"/>
  <testcase classname="testcases.DesignationFolder" name="verifyGetAllDesignationWithoutAuthorization" time="0.032"/>
  <testcase classname="testcases.DesignationFolder" name="updateDesignationWithoutAuthorization" time="0.131"/>
  <testcase classname="testcases.DesignationFolder" name="deleteSingleDesignationWithoutAuthorization" time="0.036"/>
  <testcase classname="testcases.DesignationFolder" name="verifyAddDesignationWithAuthorization" time="0.841">
    <failure type="java.lang.AssertionError" message="expected [No designation to delete with Unprocessable Entity.] but found [No status to delete with designation,Unprocessable Entity.]">
      <![CDATA[java.lang.AssertionError: expected [No designation to delete with Unprocessable Entity.] but found [No status to delete with designation,Unprocessable Entity.]
at testcases.DesignationFolder.deleteSingleDesignationWithAuthorization(DesignationFolder.java:357)
at testcases.DesignationFolder.verifyAddDesignationWithAuthorization(DesignationFolder.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddDesignationWithAuthorization -->
  <testcase classname="testcases.DesignationFolder" name="addDesignationWithInvalidPayload" time="0.693"/>
  <testcase classname="testcases.DesignationFolder" name="addDesignationWithSamePayloadAsPrevious" time="0.551"/>
  <testcase classname="testcases.DesignationFolder" name="verifyGetAllDesignationWithAuthorization" time="0.44"/>
  <testcase classname="testcases.DesignationFolder" name="updateDesignationWithAuthorization" time="0.443"/>
  <testcase classname="testcases.DesignationFolder" name="updateDesignationWithoutGivingDesignationId" time="0.41"/>
  <testcase classname="testcases.DesignationFolder" name="updateDesignationByGivingNonExistingDesignationId" time="0.391"/>
  <testcase classname="testcases.DesignationFolder" name="deleteSingleDesignationWithInvalidDesignationName" time="0.402">
    <failure type="java.lang.AssertionError" message="expected [No designation to delete with Lawyer2.] but found [No status to delete with designation,Unprocessable Entity,Lawyer2.]">
      <![CDATA[java.lang.AssertionError: expected [No designation to delete with Lawyer2.] but found [No status to delete with designation,Unprocessable Entity,Lawyer2.]
at testcases.DesignationFolder.deleteSingleDesignationWithInvalidDesignationName(DesignationFolder.java:400)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- deleteSingleDesignationWithInvalidDesignationName -->
  <testcase classname="testcases.RegularTaskFolder" name="verifyAddRegularTaskWithoutAuthorization" time="0.032"/>
  <testcase classname="testcases.RegularTaskFolder" name="verifyGetAllRegularTaskForEmployeeWithoutAuthorization" time="0.024"/>
  <testcase classname="testcases.RegularTaskFolder" name="verifyUpdateRegularTaskWithoutAuthorization" time="0.027"/>
  <testcase classname="testcases.RegularTaskFolder" name="deleteSingleStatusWithoutAuthorization" time="0.022"/>
  <testcase classname="testcases.RegularTaskFolder" name="verifyAddRegularTaskWithAuthorization" time="0.9"/>
  <testcase classname="testcases.RegularTaskFolder" name="addRegularTaskWithSamePayloadAsPrevious" time="0.446"/>
  <testcase classname="testcases.RegularTaskFolder" name="addRegularTaskWithInvalidPayload" time="0.392"/>
  <testcase classname="testcases.RegularTaskFolder" name="verifyGetAllRegularTaskWithAuthorization" time="0.383"/>
  <testcase classname="testcases.RegularTaskFolder" name="verifyGetAllRegularTaskWithInvalidEmployeeId" time="0.393"/>
  <testcase classname="testcases.RegularTaskFolder" name="verifyUpdateRegularTaskWithAuthorization" time="0.387"/>
  <testcase classname="testcases.RegularTaskFolder" name="updateStatusWithoutGivingRegularTaskId" time="0.386"/>
  <testcase classname="testcases.RegularTaskFolder" name="updateStatusByGivingNonExistingRegularTaskId" time="0.478"/>
  <testcase classname="testcases.RegularTaskFolder" name="deleteSingleRegularTaskWithInvalidRegularTaskId" time="0.46"/>
  <testcase classname="testcases.RoleFolder" name="verifyAddRoleWithoutAuthorization" time="0.155"/>
  <testcase classname="testcases.RoleFolder" name="verifyGetAllRoleWithoutAuthorization" time="0.032"/>
  <testcase classname="testcases.RoleFolder" name="updateRoleWithoutAuthorization" time="0.058"/>
  <testcase classname="testcases.RoleFolder" name="deleteSingleRoleWithoutAuthorization" time="0.046"/>
  <testcase classname="testcases.RoleFolder" name="getRoleByLevelWithoutAuthorization" time="0.049"/>
  <testcase classname="testcases.RoleFolder" name="verifyAddRoleWithAuthorization" time="0.879">
    <failure type="java.lang.AssertionError" message="Invalid status code expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: Invalid status code expected [200] but found [400]
at testcases.RoleFolder.deleteSingleRoleWithAuthorization(RoleFolder.java:416)
at testcases.RoleFolder.verifyAddRoleWithAuthorization(RoleFolder.java:148)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddRoleWithAuthorization -->
  <testcase classname="testcases.RoleFolder" name="addRoleWithSamePayloadAsPrevious" time="0.429"/>
  <testcase classname="testcases.RoleFolder" name="addRoleWithInvalidPayload" time="0.515"/>
  <testcase classname="testcases.RoleFolder" name="addRoleWithSameRoleLevelInPayloadAsPrevious" time="0.516">
    <failure type="java.lang.AssertionError" message="expected [Role Already Exists] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Role Already Exists] but found [null]
at testcases.RoleFolder.addRoleWithSameRoleLevelInPayloadAsPrevious(RoleFolder.java:257)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- addRoleWithSameRoleLevelInPayloadAsPrevious -->
  <testcase classname="testcases.RoleFolder" name="verifyGetAllRoleWithAuthorization" time="0.47"/>
  <testcase classname="testcases.RoleFolder" name="updateRoleWithAuthorization" time="0.528">
    <failure type="java.lang.AssertionError" message="expected [Producer] but found [ROLE_PRODUCER]">
      <![CDATA[java.lang.AssertionError: expected [Producer] but found [ROLE_PRODUCER]
at testcases.RoleFolder.updateRoleWithAuthorization(RoleFolder.java:312)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- updateRoleWithAuthorization -->
  <testcase classname="testcases.RoleFolder" name="updateRoleWithoutGivingRoleId" time="0.451"/>
  <testcase classname="testcases.RoleFolder" name="updateRoleByGivingNonExistingRoleId" time="0.459"/>
  <testcase classname="testcases.RoleFolder" name="deleteSingleRoleWithInvalidRoleId" time="1.33"/>
  <testcase classname="testcases.RoleFolder" name="getRoleByLevelWithAuthorization" time="0.491">
    <failure type="java.lang.AssertionError" message="Invalid status code expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Invalid status code expected [200] but found [404]
at testcases.RoleFolder.getRoleByLevelWithAuthorization(RoleFolder.java:469)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- getRoleByLevelWithAuthorization -->
  <testcase classname="testcases.RoleFolder" name="getRoleByLevelWithInvalidRoleLevel" time="0.506"/>
  <testcase classname="testcases.TagFolder" name="verifyAddTagWithoutAuthorization" time="0.047"/>
  <testcase classname="testcases.TagFolder" name="verifyGetAllTagWithoutAuthorization" time="0.025"/>
  <testcase classname="testcases.TagFolder" name="updateTagWithoutAuthorization" time="0.107"/>
  <testcase classname="testcases.TagFolder" name="deleteSingleTagWithoutAuthorization" time="0.024"/>
  <testcase classname="testcases.TagFolder" name="verifyAddTagWithAuthorization" time="0.905"/>
  <testcase classname="testcases.TagFolder" name="addTagWithSamePayloadAsPrevious" time="0.525"/>
  <testcase classname="testcases.TagFolder" name="addTagWithInvalidPayload" time="0.485"/>
  <testcase classname="testcases.TagFolder" name="verifyGetAllTagWithAuthorization" time="0.388"/>
  <testcase classname="testcases.TagFolder" name="updateTagWithAuthorization" time="0.536"/>
  <testcase classname="testcases.TagFolder" name="updateTagWithoutGivingTagId" time="0.499"/>
  <testcase classname="testcases.TagFolder" name="updateTagByGivingNonExistingTagId" time="0.411"/>
  <testcase classname="testcases.TagFolder" name="deleteSingleTagWithInvalidTagName" time="0.384">
    <failure type="java.lang.AssertionError" message="expected [No tag to delete with Software Company.] but found [No tag to delete with tag,QA,Software Company.]">
      <![CDATA[java.lang.AssertionError: expected [No tag to delete with Software Company.] but found [No tag to delete with tag,QA,Software Company.]
at testcases.TagFolder.deleteSingleTagWithInvalidTagName(TagFolder.java:393)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- deleteSingleTagWithInvalidTagName -->
  <testcase classname="testcases.PriorityFolder" name="verifyAddPriorityWithoutAuthorization" time="0.023"/>
  <testcase classname="testcases.PriorityFolder" name="verifyGetAllPriorityWithoutAuthorization" time="0.024"/>
  <testcase classname="testcases.PriorityFolder" name="updatePriorityWithoutAuthorization" time="0.028"/>
  <testcase classname="testcases.PriorityFolder" name="verifyAddPriorityWithAuthorization" time="0.809"/>
  <testcase classname="testcases.PriorityFolder" name="addPriorityWithSamePayloadAsPrevious" time="0.405"/>
  <testcase classname="testcases.PriorityFolder" name="addPriorityWithInvalidPayload" time="0.609"/>
  <testcase classname="testcases.PriorityFolder" name="addStatusWithSamePriorityLevelInPayloadAsPrevious" time="0.445"/>
  <testcase classname="testcases.PriorityFolder" name="verifyGetAllPriorityWithAuthorization" time="0.398"/>
  <testcase classname="testcases.PriorityFolder" name="updatePriorityWithAuthorization" time="0.442">
    <failure type="java.lang.AssertionError" message="expected [Global] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Global] but found [null]
at testcases.PriorityFolder.updatePriorityWithAuthorization(PriorityFolder.java:301)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- updatePriorityWithAuthorization -->
  <testcase classname="testcases.PriorityFolder" name="updatePriorityWithoutGivingPriorityId" time="0.514"/>
  <testcase classname="testcases.PriorityFolder" name="updatePriorityByGivingNonExistingPriorityId" time="0.469"/>
  <testcase classname="testcases.PriorityFolder" name="deleteSinglePriorityWithInvalidPriorityName" time="0.387">
    <failure type="java.lang.AssertionError" message="expected [No priority to delete with Master2.] but found [No priority to delete with Investor,Master2.]">
      <![CDATA[java.lang.AssertionError: expected [No priority to delete with Master2.] but found [No priority to delete with Investor,Master2.]
at testcases.PriorityFolder.deleteSinglePriorityWithInvalidPriorityName(PriorityFolder.java:430)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- deleteSinglePriorityWithInvalidPriorityName -->
</testsuite> <!-- Test -->
